sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-eu-central-1.aliyuncs.com
    access-key-id: LTAI5tPU3Y4dYhi1AePc9jZ9
    access-key-secret: eeZ6RUFPfxssNGvSCpAvar7ZjOHvcq
    bucket-name: takeout-demo